import re

FPOS_COMBINATIONS = ['ADJ_NOUN', 'ADJ', 'ADP_ADJ', 'ADP_NOUN',
                     'ADV_ADV', 'ADV_NOUN', 'ADV_VERB', 'ADV', 'CONJ_ADV',
                     'CONJ', 'NOUN_ADJ', 'NOUN_ADV', 'NOUN_NOUN',
                     'NOUN_PART', 'NOUN_VERB', 'NOUN', 'NUM_NOUN',
                     'PART_VERB', 'PRON_NOUN', 'PRON_PRON', 'PRON',
                     'VERB_ADJ', 'VERB_ADP', 'VERB_ADV', 'VERB_NOUN',
                     'VERB_PRON', 'VERB', 'NOUN']

# ToDO: analyze morph features in spaCy ->
VOCAB_RU = {
    'morph_feats': ['Animacy_Anim', 'Animacy_Inan', 'Aspect_Imp', 'Aspect_Perf',
                    'Case_Acc', 'Case_Dat', 'Case_Gen', 'Case_Ins', 'Case_Nom', 'Case_Loc', 'Case_Voc',
                    'Comparision_Cmp', 'Comparision_Sup', 'Degree_Pos',
                    'Gender_Fem', 'Gender_Masc', 'Gender_Neut', 'Number_Plur', 'Number_Sing',
                    'Person_1', 'Person_2', 'Person_3', 'Tense_Imp',  # UDPipe-based features
                    'Tense_Past',
                    'Valency_INTR', 'Valency_TR', 'Variant_Brev', 'VerbForm_Fin',
                    'VerbForm_Ger', 'VerbForm_Inf', 'VerbForm_Part',
                    'Voice_Act', 'Voice_Pass',
                    'fPOS_ADJ', 'fPOS_ADP', 'fPOS_ADV', 'fPOS_CONJ', 'fPOS_INTJ', 'fPOS_NOUN', 'fPOS_NUM',
                    'fPOS_PART', 'fPOS_PRON', 'fPOS_VERB', 'fPOS_X',
                    # Next features from SpaCy -->
                    'Person_First', 'Person_Second', 'Person_Third', 'Voice_Mid',
                    'VerbForm_Conv',
                    'Tense_Pres', 'Tense_Fut',
                    'Mood_Ind', 'Mood_Imp', 'Mood_Cnd',
                    'Polarity_Neg', 'Foreign_Yes',
                    'StyleVariant_Short',
                    'Case_Par',
                    'Degree_Cmp', 'Degree_Sup',
                    ],
    'ner_tags': ['PER', 'LOC', 'ORG'],
    'count_words_x': [r'\bвопрос', r'\bявля[ею]', r'\bчто\b', r'\bно\b', r'\bтам', r'действительно', r'\bта',
                      r'\bв\b', r'\bеще', r'\bв [а-я]+[еи]', r'\bвопрос', r'\bили\b', r'кроме э?того', r'будучи',
                      r'\bи\b', r'во?-[а-я]+х', r'–', r'пути', r'\bсам[ое]', r'кажется', r'котор',
                      r'\b\d+\b', r'(?:%|процент)',
                      r'\b([1-9]|0[1-9]|1[0-9]|2[0-9]|3[0-1])(\.|-|/)([1-9]|0[1-9]|1[0-2])(\.|-|/)([0-9][0-9]|19[0-9][0-9]|20[0-9][0-9])$|^([0-9][0-9]|19[0-9][0-9]|20[0-9][0-9])(\.|-|/)([1-9]|0[1-9]|1[0-2])(\.|-|/)([1-9]|0[1-9]|1[0-9]|2[0-9]|3[0-1])\b',
                      r'\$?(?:(?:[1-9][0-9]{0,2})(?:,[0-9]{3})+|[1-9][0-9]*|0)(?:[\.,][0-9][0-9]?)?(?![0-9]+)'
                      ],
    'count_words_y': [r'\bтем\b', r'\bв\b', r'\bеще', r'\bили\b', r'\bко?\b', r'\bн[е|и]\b',
                      r'\bпосле\b', r'\bсам[ое]', r'\bта', r'\bтак\b', r'\bте', r'\bто ?', r'\bчто\b', r'\bявля[ею]',
                      r'во?-[а-я]+х', r'кажется', r'котор', r'кроме э?того', r'несмотря', r'основ', r'перед',
                      r'последн', r'пути', r'только', r'–',
                      r'\b\d+\b',  # number
                      r'\b([1-9]|0[1-9]|1[0-9]|2[0-9]|3[0-1])(\.|-|/)([1-9]|0[1-9]|1[0-2])(\.|-|/)([0-9][0-9]|19[0-9][0-9]|20[0-9][0-9])$|^([0-9][0-9]|19[0-9][0-9]|20[0-9][0-9])(\.|-|/)([1-9]|0[1-9]|1[0-2])(\.|-|/)([1-9]|0[1-9]|1[0-9]|2[0-9]|3[0-1])\b',
                      # date
                      r'\b\d+\b', r'(?:%|процент)',
                      r'\$?(?:(?:[1-9][0-9]{0,2})(?:,[0-9]{3})+|[1-9][0-9]*|0)(?:[\.,][0-9][0-9]?)?(?![0-9]+)'
                      # currency
                      ],
    'markers_by_classes': {
        'condition': [r'\bесли\b', r'\bежели\b', r'\bкабы\b', r'\bпри условии', r'\bв случае\b' r'\bпока\b',
                      r'\bкогда\b',
                      r'\bпри\b', r'\bвне зависимости\b', r'\bна условиях', r'\bни при каких\b', r'\bто\b'],
        'purpose': [r'\bдля\b', r'\bдабы\b', r'\bради\b', r'\bв надежде\b', r'\bс намерением\b', r'\bс целью\b',
                    r'\bчтобы?\b', r'\bнужно\b', r'\bнужен\b', r'\bнужна\b', r'\bнеобходим', ],
        'solutionhood': [r'\?', r'\bли\b', r'почему', r'зачем', r'отчего', r'\bчто же\b', r'\bкто знает\b', r'откуда',
                         r'\bгде\b'],
        'attribution': [r'\bорет\b', r'\bору\b', r'\b([сc])\b', r'беседовал', r'брюзж[уиа]', r'\bв заявлении',
                        r'\bв произведении', '\bв статье', 'веща(ю|ешь|ет)', 'возра[зж]', 'выводу приш', 'выражу',
                        r'выразил', r'высказывал', r'выступил', r'говори', r'говоря словами', r'добави', r'догадал',
                        r'\bдума[ею]т?\b', r'жалу[ею]тся', r'заключ(а[ею]|ил)', r'заметил', r'замечал', r'заявил',
                        r'заявля',
                        r'\bзнаю\b', r'\bимхо\b', r'интересуется', r'кажется', r'\bкак пишет', r'\bкак пишут',
                        r'\bкак сказа', r'командовал', r'командует', r'командуют', r'констатир', r'кричит', r'кричу',
                        r'можно сказать', r'\bна (мой|твой|ваш|его|ее|их) взгляд', r'надеюсь', r'напоминае',
                        r'напоминаю',
                        r'напомнил', r'\bною\b', r'\bныл\b', r'обещает', r'обещают', r'объявил', r'объявят',
                        r'объяснил ',
                        r'объясню', r'объясня', r'описал', r'определил', r'отметил', r'отмеча', r'отмечу', r'передает',
                        r'писал', r'писать', r'пишет', r'пишут', r'по данным',
                        r'\bпо (моему|твоему|вашему|его|ее|их|общепринятой|общепринятому)? ?(логике|мнению|оценкам|словам|сведениям)',
                        r'\bпо закону', r'\bпо информации', r'\bпо этой информации', r'\bподозрева', r'подтвер',
                        r'подчеркива[ею]т', r'подчеркну', r'подытожил', r'понимае', r'понимаю', r'понял', r'пояснил',
                        r'поясню', r'поясня', r'предлага', r'предпол', r'предупредил', r'предупрежда', r'призвал',
                        r'признал', r'рапорт', r'рассужд', r'резюмирует', r'свидетельств', r'сказал', r'сказать',
                        r'\bсо словами', r'согласно', r'сообщае', r'сообщаю', r'сообщени', r'сообщил',
                        r'сход[ия]тся во мнении', r'\bсчита', r'точки зрения', r'\bуведом', r'\bузнал', r'\bуказом\b',
                        r'\bуказу\b', r'указыва', r'утвержда', r'уточня', r'цитируя'],
        'contrast': [r'\bа\b', r'\bно\b', r'\bв то время как\b', r'все-таки', r'\bда и то\b', r'\bесли же\b',
                     r'\bзато\b', r'\bлишь\b', r'напротив,', r'\bне смотря на\b', r'\bоднако\b', r'\bтолько\b',
                     r'\bхотя\b'],
    },
    'pairs_words': {
        'first_pair_x': [',',
                         r'(?:а|и) вот', r'(?:за послед|на сегодняшний|в настоящее)',
                         r'(?:но|и|а|что) если', r'(?:сегодняш|современн)',
                         r'(?:я|он|она|это) не\b', r'(\( в)',
                         r'- ?', r':', r'\(', r'\)', r'\.',
                         r'\b(по)?служ[иа]',
                         r'\bа\b', r'\bбы\b', r'\bбыл\b', r'\bбыть\b', r'\bв [а-я]+[еи]',
                         r'\bв\b', r'\bважн', r'\bведь\b', r'\bвид.?\b', r'\bвидно\b', r'\bво\b', r'\bвопрос',
                         r'\bвот\b', r'\bвсе\b', r'\bвтор', r'\bвывод\b', r'\bгде\b', r'\bда\b', r'\bдела',
                         r'\bдо\b', r'\bему\b', r'\bеще', r'\bже\b', r'\bза\b', r'\bзаканчива',
                         r'\bи\b', r'\bиз\b', r'\bили\b', r'\bим\b', r'\bисходя\b', r'\bитог.\b', r'\bих\b',
                         r'\bкак (?!по|о|у)(?!каз)', r'\bко?\b', r'\bли\b', r'\bлица\b', r'\bлишь\b',
                         r'\bмере\b', r'\bмог', r'\bмомент\b', r'\bмы\b', r'\bн[е|и]\b', r'\bна\b',
                         r'\bнам\b', r'\bнего', r'\bних\b', r'\bно\b', r'\bоб?\b', r'\bобщ[иеу]', r'\bот\b',
                         r'\bперв', r'\bпо\b', r'\bпод\b', r'\bпока\b',
                         r'\bсам[ое]', r'\bсвязи\b', r'\bсилу\b', r'\bситуаци', r'\bслова\b', r'\bсловам\b', r'\bсо\b',
                         r'\bта', r'\bтак(?:ие|им|их|ов|ой|ая|ое)\b', r'\bтак\b', r'\bтакже\b', r'\bтам\b',
                         r'\bте[мх]?',
                         r'\bто\b', r'\bтого\b', r'\bтом\b', r'\bтому\b', r'\bтот\b', r'\bточк(?:и|ой)', r'\bтут\b',
                         r'\bуже\b', r'\bуказа', r'\bфакт\b', r'\bцель', r'\bчаще\b', r'\bчего\b', r'\bчем\b',
                         r'\bчто [а-я]+ет\b', r'\bчто\b', r'\bэтим\b', r'\bэто[ймг]\b', r'\bэто\b',
                         r'\bявля[ею]',
                         r'\d+', r'анализ', r'более( того)?', r'больш[оаи]', r'больше', r'буд[еу][мт]',
                         r'в (?:начале|январе|феврале|марте|апреле|мае|июне|июле|августе|сентябре|октябре|ноябре|декабре)',
                         r'в (?:статье|результате)', r'\bв большинстве', r'\bв качестве', r'\bв одном', r'\bв свою',
                         r'\bв то', r'\bвести\b', r'\bвключа', r'вместе', r'\bврем', r'всего', r'вызы?ва', r'главное',
                         r'\bговорят?\b', r'\bдаже\b', r'далее', r'\bданн', r'действительно', r'делать',
                         r'для ', r'для\b', r'до .+(?:ия|а)', r'добави', r'должны', r'друго', r'если бы', r'если',
                         r'естественно', r'есть', r'зависимост', r'задач', r'заключа', r'заключение',
                         r'заме(?:ти|чать)', r'застав[ли]', r'заяв(?:и|ля)', r'здесь', r'значени', r'значит', r'игра',
                         r'ид(?:ет|ти)', r'извест(?:ен|но)', r'изменя', r'име(?:я|ем|ет|ют)', r'имени', r'именно',
                         r'имя', r'ин[?:ое|ой|ая]', r'интересн', r'информаци', r'к концу', r'кажется', r'казалось бы',
                         r'как (?:отмеч|счита)', r'как (?:пишет|заявил|отмеча|счита)', r'как (?:по|у)каз',
                         r'как (?:сообщ|заяв)', r'как вид', r'как только', r'как(?:ая|ой|ое|ие)', r'качестве',
                         r'когда', r'конечн', r'конце', r'котор', r'кроме того', r'между', r'месте', r'мнени',
                         r'может', r'можно', r'на (?:наш|их|его|ее)\b', r'наблюдени', r'назва', r'называ', r'например',
                         r'настоящ', r'начал[аеоу]', r'начина', r'некотор', r'необходим', r'несмотря на', r'несомненно',
                         r'\bниве\b', r'\bно тут\b', r'нужно', r'обвини', r'образом', r'обстоятельств', r'объект',
                         r'объяви', r'объясн', r'обязательн', r'однако', r'одним', r'одновременно', r'означа',
                         r'\bоказ', r'описание', r'определ', r'основ', r'особ', r'особенн', r'отвечая', r'отличи',
                         r'отмети', r'отмеч', r'отношении', r'оценк', r'оценка', r'очевид', r'первоначально',
                         r'\bперед', r'\bписа', r'по (?:мнению|его|ее|их|словам|данным|сведениям|закону)', r'повыш',
                         r'подобн', r'подтвержд', r'подход', r'подчерк', r'поз(?:дн|же)', r'позволя',
                         r'позволяющ', r'показ', r'получается', r'помо[чщ]', r'помога', r'пос[кт]ольку', r'после',
                         r'потому', r'предназначен', r'представ', r'при э?том', r'привести', r'приводи', r'призна',
                         r'пример', r'причем', r'причин', r'просто', r'против', r'проявля', r'пусть', r'равно', r'ради',
                         r'разве', r'раздел', r'район', r'рамках', r'ранее', r'распоряж', r'рассказыва', r'рассм[ао]тр',
                         r'результат', r'речь', r'решение', r'роли', r'с (?:ее|его)', r'с одной', r'с точки',
                         r'сведениям',
                         r'свидетельств', r'связан', r'сдела', r'сказа', r'скорее', r'следует', r'следующ',
                         r'слишком', r'случа', r'смену', r'собственно', r'согласно', r'сожален', r'сообща', r'сообщи',
                         r'соответств', r'список', r'стоит', r'столь', r'сторон', r'существен', r'так как',
                         r'так что', r'теперь', r'течение', r'только', r'требуется', r'у (?:меня|нас|них|него|нее)',
                         r'указыва', r'услови', r'утвержда', r'учетом', r'учитыва', r'форме', r'ходе', r'хотя',
                         r'через',
                         r'что ж', r'что же', r'что касается', r'чтобы', r'шаг ', r'широк', r'–',
                         ],
        'last_pair_x': [',$', r'!$', r'(?:один|одна|одно|одни)', r'(?:сегодняш|современн)', r';$', r'[-—]', r'\(',
                        r'\)', r'\.$', r'\?$', r'\bа\b', r'\bбез\b', r'\bбы\b', r'\bбыл\b', r'\bбыть\b',
                        r'\bв [а-я]+[еи]', r'\bв\b', r'\bважн', r'\bвид.?\b', r'\bвидно\b', r'\bво\b', r'\bвопрос',
                        r'\bвтор', r'\bвывод\b', r'\bдела', r'\bеще', r'\bже\b', r'\bза\b', r'\bи\b', r'\bиз\b',
                        r'\bили\b', r'\bим\b', r'\bитог.\b', r'\bих\b', r'\bкак\b', r'\bко?\b', r'\bлица\b',
                        r'\bлишь\b', r'\bмало\b', r'\bмере\b', r'\bмог', r'\bмомент\b', r'\bн[е|и]\b', r'\bна\b',
                        r'\bнего', r'\bних\b', r'\bоб?\b', r'\bобщ[иеу]', r'\bот\b', r'\bперв', r'\bпор\b', r'\bрода\b',
                        r'\bс\b', r'\bсам[ое]', r'\bсвязи\b', r'\bсилу\b', r'\bситуаци', r'\bслова\b', r'\bсловам\b',
                        r'\bсо\b', r'\bстать\b', r'\bта', r'\bтак(?:ие|им|их|ов|ой|ая|ое)\b', r'\bтак\b', r'\bтакже\b',
                        r'\bте\b', r'\bтем\b', r'\bто\b', r'\bтого\b', r'\bтом(?:\),|,|..)', r'\bтом\b',
                        r'\bтому\b', r'\bточк(?:и|ой)', r'\bуказа', r'\bфакт\b', r'\bцель', r'\bчаще\b', r'\bчем\b',
                        r'\bчто\b', r'\bэто', r'\bэто[ймг]\b', r'\bэто\b', r'\bявля[ею]', r'анализ', r'более',
                        r'больш[оаи]', r'больше', r'буд[еу][мт]', r'вести', r'выби?ра', r'вывод[ау]', r'главное',
                        r'говорить?ся', r'говоря', r'говорят?', r'грани', r'далее', r'действительно', r'делать', r'для',
                        r'для\b', r'добави', r'должны', r'друго', r'есть', r'заключа', r'заме(?:ти|чать)', r'затем',
                        r'заяв(?:и|ля)', r'здесь', r'значени', r'значит', r'зрения', r'игра', r'ид(?:ет|ти)',
                        r'извест(?:ен|но)', r'известно', r'име(?:я|ем|ет|ют)', r'имени', r'ин[?:ое|ой|ая]',
                        r'информаци', r'иными?', r'кажется', r'конечн', r'котор', r'маловероятн', r'между', r'менее',
                        r'месте', r'мире', r'мнени', r'можно', r'наблюдени', r'наде[еюя]ть?ся', r'назва', r'называ',
                        r'наоборот', r'направлен', r'настоящ', r'начал[аеоу]', r'начина', r'независим', r'некотор',
                        r'ниве', r'нужно', r'обвини', r'обнаружи', r'образом', r'обстоятельств', r'объект', r'объяви',
                        r'объясн', r'одновременно', r'означа', r'оказ', r'определ', r'основ', r'особ', r'особенн',
                        r'отличи', r'отмети', r'отмеч', r'отношении', r'оценк', r'очевид', r'переда', r'писа', r'повод',
                        r'повыш', r'подобн', r'подтвержд', r'подход', r'подчерк', r'поз(?:дн|же)', r'позволя', r'показ',
                        r'получа', r'пользу', r'помо[чщ]', r'помога', r'после', r'послужи', r'потому', r'предмет',
                        r'предназначен', r'представ', r'приводи', r'призна', r'пример', r'приходится', r'причин',
                        r'проведен', r'против', r'противн', r'пути', r'равно', r'ради', r'разве', r'раздел', r'район',
                        r'ранее', r'рассказыва', r'рассм[ао]тр', r'результат', r'речь', r'решение', r'роли', r'роль',
                        r'свидетельств', r'связан', r'сдела', r'сказа', r'следует', r'следующ', r'случа', r'собственно',
                        r'сообща', r'сообщи', r'стоит', r'столь', r'сторон', r'существен', r'теперь', r'только',
                        r'\bтреб', r'указыва', r'услови', r'уточня', r'учитыва', r'форме', r'ходе', r'хотя', r'целях',
                        r'части', r'частности', r'через', r'числ', r'широк', r'–', r'рассчитывая', ],

        'first_pair_y': [',$', r'"', r'$служ', r'$целях', r'(?:естественно|предполож)', r'(?:сегодняш|современн)',
                         r'(?:сказал|отме|заметил|пишет|подчеркнул|пояснил|говорит)', r'(\( в)', r'- в', r':', r'[-―]',
                         r'\(', r'\)', r'\.', r'\bа\b', r'\bаналогичн', r'\bбез\b', r'\bбы\b', r'\bбыл\b', r'\bбыть\b',
                         r'\bв [а-я]+[еи]', r'\bв\b', r'\bважн', r'\bведь\b', r'\bвид.?\b', r'\bвидно\b',
                         r'\bвключая\b', r'\bво\b', r'\bвопрос', r'\bвот\b', r'\bвсе\b', r'\bвслед\b', r'\bвтор',
                         r'\bвывод\b', r'\bговори.?\b', r'\bда\b', r'\bдава', r'\bдела', r'\bдело\b', r'\bдо\b',
                         r'\bему\b', r'\bеще', r'\bже\b', r'\bза\b', r'\bзаканчива', r'\bи если', r'\bи при\b',
                         r'\bи\b', r'\bибо\b', r'\bиз\b', r'\bили\b', r'\bим\b', r'\bисходя\b', r'\bитог.\b', r'\bих\b',
                         r'\bкак\b', r'\bко?\b', r'\bли\b', r'\bлибо\b', r'\bлишь\b', r'\bмало\b', r'\bмере\b',
                         r'\bмог', r'\bмомент\b', r'\bмы\b', r'\bн[е|и]\b', r'\bна\b', r'\bнам\b', r'\bнего',
                         r'\bних\b', r'\bно\b', r'\bоб?\b', r'\bобщ[иеу]', r'\bот\b', r'\bперв', r'\bпо\b', r'\bпод\b',
                         r'\bпока\b', r'\bс\b', r'\bсам[ое]', r'\bсамым\b', r'\bсвязи\b', r'\bсилу\b', r'\bситуаци',
                         r'\bследстви', r'\bслова\b', r'\bсловам\b', r'\bсо\b', r'\bсреди\b', r'\bстать\b', r'\bта',
                         r'\bтак(?:ие|им|их|ов|ой|ая|ое)\b', r'\bтак\b', r'\bтакже\b', r'\bтам\b', r'\bте', r'\bтем\b',
                         r'\bтех\b', r'\bто ?', r'\bто\b', r'\bтого\b', r'\bтом\b', r'\bтому\b', r'\bтот\b',
                         r'\bточк(?:и|ой)', r'\bтут\b', r'\bуже\b', r'\bуказа', r'\bфакт\b', r'\bцель', r'\bчаще\b',
                         r'\bчего\b', r'\bчем\b', r'\bчему\b', r'\bчто [а-я]+ет\b', r'\bчто и\b', r'\bчто\b',
                         r'\bэтим\b', r'\bэто', r'\bэто[ймг]\b', r'\bэто\b', r'\bявля[ею]', r'^[-—]', r'img', r'«',
                         r'а в', r'авторы', r'анализ', r'благодаря', r'более', r'больш[оаи]', r'больше', r'буд[еу][мт]',
                         r'будем', r'в (?:результате|работе|качестве)', r'в котор(?:ом|ых)', r'в общем', r'в э?том',
                         r'вести', r'включа', r'вместо', r'врем', r'всего', r'выби?ра', r'вывод', r'вызы?ва',
                         r'главное', r'говорить?ся', r'говоря', r'говорят?', r'грани', r'да и', r'даже', r'далее',
                         r'дальше', r'данн', r'действительно', r'делать', r'для (?:решения|этого)', r'для', r'для\b',
                         r'довольно', r'должны', r'други', r'друго', r'если', r'естественно', r'есть', r'за счет',
                         r'завери', r'зависимост', r'задач', r'заключа', r'застав[ли]', r'затем', r'заяв(?:и|ля)',
                         r'здесь', r'значени', r'значит', r'и (?:в|что|для|на)', r'и даже', r'и как', r'и не', r'и при',
                         r'игра', r'ид(?:ет|ти)', r'извест(?:ен|но)', r'известно', r'изменя', r'име(?:я|ем|ет|ют)',
                         r'имени', r'именно', r'имя', r'ин[?:ое|ой|ая]', r'информаци', r'как сообщ',
                         r'как(?:ая|ой|ое|ие)', r'качестве', r'когда', r'конце', r'котор', r'которые', r'между',
                         r'менее', r'месте', r'мнени', r'может', r'можно', r'\bна (?:мой|его|их|наш|ее)', r'наблюдени',
                         r'называ', r'намека', r'наоборот', r'направлен', r'направленн', r'настоящ', r'начал[аеоу]',
                         r'начина', r'невозможн', r'независим', r'неимением', r'некотор', r'необходим', r'несмотря',
                         r'ниве', r'нужно', r'о чем', r'об этом', r'обеспечивающ', r'обнаружи', r'обнаружил',
                         r'образом', r'обстоятельств', r'объект', r'объяви', r'объясн', r'обязательн', r'однако',
                         r'одним', r'одновременно', r'означа', r'оказ', r'определ', r'основ', r'особ', r'особенн',
                         r'откуда', r'отличи', r'отместку', r'отмети', r'отмеч', r'отношении', r'оценк', r'оценка',
                         r'очевид', r'первоначально', r'перед', r'переда', r'писа', r'повыш', r'подобн', r'подтвержд',
                         r'подход', r'подчерк', r'поз(?:дн|же)', r'позволя', r'позволя', r'показ', r'получа', r'пользу',
                         r'помо[чщ]', r'помога', r'порожд', r'порожда', r'пос[кт]ольку', r'после', r'потому', r'почему',
                         r'поэтому', r'правда', r'предназначен', r'представ', r'при э?том', r'привести', r'приводи',
                         r'призна', r'пример', r'приходится', r'причем', r'причин', r'проведен', r'просто', r'против',
                         r'противн', r'проявля', r'пути', r'равно', r'ради', r'разве', r'раздел', r'разделя',
                         r'разумеется', r'район', r'рамках', r'ранее', r'распоряж', r'рассказыва', r'рассм[ао]тр',
                         r'результаты?', r'речь', r'решение', r'роли', r'роль', r'сведениям', r'свидетельств',
                         r'свидетельствует', r'связан', r'сдела', r'скорее', r'следует', r'следующ', r'слишком',
                         r'случа', r'смену', r'собственно', r'согласно', r'сожален', r'сообща', r'сообщи',
                         r'соответств', r'список', r'способств', r'стоит', r'столь', r'сторон', r'строго', r'существен',
                         r'так как', r'тем не', r'теперь', r'течение', r'то (?:в|он|вы|мы|можно|нужно|следует)',
                         r'тогда', r'только', r'требуется', r'трет(?:ий|ая|ое|ьи)', r'указыва', r'услови', r'утвержда',
                         r'уточня', r'учетом', r'учитыва', r'формула', r'характеризу', r'ходе', r'хотя', r'части',
                         r'частности', r'через', r'числ', r'чтобы', r'широк', r'–'],

        'last_pair_y': [',$', ',.+', r'!$', r'"', r'(?:один|одна|одно|одни)', r'- ?', r';', r'\)', r'\?$', r'\?',
                        r'\bбыл\b', r'\bбыть\b', r'\bв [а-я]+[еи]', r'\bв\b', r'\bважн', r'\bвид.?\b', r'\bвопрос',
                        r'\bвтор', r'\bговори.?\b', r'\bдела', r'\bдело\b', r'\bему\b', r'\bеще', r'\bже\b', r'\bи\b',
                        r'\bиз\b', r'\bили\b', r'\bим\b', r'\bисточник\b', r'\bих\b', r'\bкак\b', r'\bко?\b',
                        r'\bлибо\b', r'\bмало\b', r'\bмомент\b', r'\bна\b', r'\bнего', r'\bних\b', r'\bобщ[иеу]',
                        r'\bперв', r'\bписа', r'\bпор\b', r'\bс\b', r'\bсам[ое]', r'\bсвязи\b', r'\bсилу\b',
                        r'\bситуаци', r'\bслова\b', r'\bсловам\b', r'\bта', r'\bтак(?:ие|им|их|ов|ой|ая|ое)\b',
                        r'\bтак\b', r'\bтам\b', r'\bте', r'\bтем[ау]\b', r'\bто ?', r'\bто\b', r'\bтого\b', r'\bтом\b',
                        r'\bцель', r'\bчто\b', r'\bэто', r'\bэто[ймг]\b', r'\bявля[ею]', r'^[-—]', r'анализ',
                        r'больш[оаи]', r'буд[еу][мт]', r'вести', r'врем', r'вывод', r'говорить?ся', r'грани', r'далее',
                        r'действительно', r'делать', r'други', r'есть', r'зависимост', r'заме(?:ти|чать)', r'значени',
                        r'зрения', r'игра', r'ид(?:ет|ти)', r'извест(?:ен|но|на)', r'известно', r'имени', r'имя',
                        r'ин[?:ое|ой|ая]', r'иными?', r'качестве', r'когда', r'конечн', r'конце', r'маловероятн',
                        r'мире', r'мнени', r'может', r'можно', r'наблюдени', r'надеяться', r'назва', r'называ',
                        r'наоборот', r'независим', r'неясн', r'ниве', r'обстоятельств', r'обязательн', r'одновременно',
                        r'оказ', r'определ', r'особ', r'особенн', r'оценк', r'подтвержд', r'поз(?:дн|же)', r'показ',
                        r'получа', r'помо[чщ]', r'правда', r'представ', r'призна', r'пример', r'причин', r'просто',
                        r'против', r'противн' r'ради', r'разве', r'раздел', r'разумеется', r'район', r'ранее',
                        r'рассм[ао]тр', r'речь', r'решение', r'роли', r'роль', r'свидетельств', r'связан', r'сдела',
                        r'сказа', r'следует', r'следующ', r'случа', r'сообща', r'степени', r'столь', r'только',
                        r'требуется', r'учитыва', r'целях', r'части', r'числ', r'широк', ]
    }
}

VOCAB_EN = {
    'morph_feats': ['Reflex_Yes', 'Degree_Sup', 'PunctSide_Ini', 'PunctType_Peri', 'VerbForm_Fin', 'NumType_Ord',
                    'PunctType_Brck', 'Person_3', 'NumType_Card', 'ConjType_Cmp', 'Aspect_Perf', 'Number_Sing',
                    'Degree_Cmp', 'PunctSide_Fin', 'Tense_Past', 'Definite_Def', 'Polarity_Neg', 'Degree_Pos',
                    'PronType_Art', 'VerbForm_Inf', 'Person_1', 'Gender_Fem', 'PunctType_Comm', 'Mood_Ind', 'Case_Nom',
                    'PronType_Rel', 'Gender_Neut', 'Person_2', 'PronType_Ind', 'Tense_Pres', 'Foreign_Yes',
                    'Number_Plur', 'PronType_Prs', 'VerbForm_Ger', 'Definite_Ind', 'Aspect_Prog', 'PronType_Dem',
                    'PunctType_Quot', 'Poss_Yes', 'Case_Acc', 'Gender_Masc', 'NumType_Mult', 'VerbType_Mod',
                    'VerbForm_Part', 'PunctType_Dash'],
    'ner_tags': ['CARDINAL', 'DATE', 'EVENT', 'FAC', 'GPE', 'LAW',
                 'LOC', 'MONEY', 'NORP', 'ORDINAL', 'ORG', 'PERCENT',
                 'PERSON', 'PRODUCT', 'QUANTITY', 'TIME', 'WORK_OF_ART'],
    'count_words_x': [r'\b\d+\b',  # number
                      r'\b([1-9]|0[1-9]|1[0-9]|2[0-9]|3[0-1])(\.|-|/)([1-9]|0[1-9]|1[0-2])(\.|-|/)([0-9][0-9]|19[0-9][0-9]|20[0-9][0-9])$|^([0-9][0-9]|19[0-9][0-9]|20[0-9][0-9])(\.|-|/)([1-9]|0[1-9]|1[0-2])(\.|-|/)([1-9]|0[1-9]|1[0-9]|2[0-9]|3[0-1])\b',
                      # date
                      r'(?:%|percent)',  # percentage
                      r'\$?(?:(?:[1-9][0-9]{0,2})(?:,[0-9]{3})+|[1-9][0-9]*|0)(?:[\.,][0-9][0-9]?)?(?![0-9]+)'
                      # currency
                      ],
    'count_words_y': [r'\b\d+\b',  # number
                      r'\b([1-9]|0[1-9]|1[0-9]|2[0-9]|3[0-1])(\.|-|/)([1-9]|0[1-9]|1[0-2])(\.|-|/)([0-9][0-9]|19[0-9][0-9]|20[0-9][0-9])$|^([0-9][0-9]|19[0-9][0-9]|20[0-9][0-9])(\.|-|/)([1-9]|0[1-9]|1[0-2])(\.|-|/)([1-9]|0[1-9]|1[0-9]|2[0-9]|3[0-1])\b',
                      # date
                      r'\b\d+%\b',  # percentage
                      r'\$?(?:(?:[1-9][0-9]{0,2})(?:,[0-9]{3})+|[1-9][0-9]*|0)(?:[\.,][0-9][0-9]?)?(?![0-9]+)'
                      # currency
                      ],
    'markers_by_classes': {
        'Additive': [r'\band\b', r'\bor\b', r'\balso\b', r'\bmuch\b', r'\bthen\b', r'\bfurther\b', r'\bas well\b',
                     r'\bagain\b', r'\beither [. ]+ or\b\b', r'\bwhether [. ]+ or\b\b', r'\btoo\b', r'\bin particular\b',
                     r'\bin addition\b', r'\bnor\b', r'\bincreasingly\b', r'\bnot only [. ]+ but\b also\b',
                     r'\bmuch more\b', r'\bmoreover\b', r'\bfurthermore\b', r'\bmore\b', r'\bapart from\b', r'\band also\b',
                     r'\bin this way\b', r'\bneither [. ]+ nor\b\b', r'\bequally\b', r'\bneither\b', r'\btoo\b',
                     r'\baside\b', r'\babove all\b', r'\balternatively\b', r'\blikewise\b', r'\bin the same way\b',
                     r'\beither\b', r'\badditionally\b', r'\bsimilarly\b', r'\bcorrespondingly\b', r'\bor else\b',
                     r'\bbeside\b', r'\bwhat is more\b', r'\bminus\b', r'\bfurthering\b', r'\bby the same token\b',
                     r'\bplus\b', r'\bjust in case\b', r'\bon top of that\b', r'\bin just this way\b',
                     r'\bnot[. ]+ either\b', r'\banother interesting aspect\b', r'\baside from this\b',
                     r'\bjust one aspect\b', r'\bpiece by piece\b', r'\bcap it\b', r'\bcrown it all\b', r'\btop it off\b',
                     r'\bon top of it all\b'],
        'Apposition': [r'\bsuch as\b', r'\bfor example\b', r'\bparticularly\b', r'\be\.g.\b', r'\bfor instance\b',
                       r'\bi\.e\.\b', r'\bthat is\b', r'\bto show\b', r'\bspecifically\b', r'\bin this case\b',
                       r'\bnamely\b', r'\bin other words\b', r'\bdemonstrate\b', r'\bindeed\b', r'\bthus\b', r'\balike\b',
                       r'\bas an example\b', r'\banother example\b', r'\bmore precisely\b', r'\bthe following example\b',
                       r'\bsupport that\b', r'\bput it another way\b', r'\bwhich is to say\b', r'\bthat is to say\b',
                       r'\bas illustrated by\b', r'\bas an illustration of\b', r'\bviz\b', r'\bas revealed by\b',
                       r'\bthe example above\b', r'\bthe previous example\b', r'\bfor one thing\b',
                       r'\bthe example below\b', r'\bto illustrate\b', r'\bbe exact\b', r'\ba rare example of\b',
                       r'\ba notable example of\b', r'\bput it bluntly\b', r'\bput it mildly\b', r'\bwithout a doubt\b',
                       r'\bwhat i mean is\b'],
        'Clarification': [r'\beven\b', r'\bright\b', r'\busually\b', r'\bindeed\b', r'\bin terms of\b', r'\bespecially\b',
                          r'\baccording to\b', r'\bthe fact that\b', r'\bgenerally\b', r'\bcertainly\b', r'\bin fact\b',
                          r'\bof course\b', r'\blargely\b', r'\bactually\b', r'\bsignificantly\b', r'\bin general\b',
                          r'\bstress\b', r'\bapparently\b', r'\bessentially\b', r'\bextremely\b', r'\bon the basis of\b',
                          r'\bconcerning\b', r'\bconsidering\b', r'\bno doubt\b', r'\binevitably\b', r'\bdepends on\b',
                          r'\bwith respect to\b', r'\blike\b', r'\bas far as\b', r'\bunfortunately\b', r'\bprobability\b',
                          r'\bundoubtedly\b', r'\bmostly\b', r'\beven when\b', r'\bto some extent\b', r'\bby no means\b',
                          r'\bas for\b', r'\bevidently\b', r'\bmoreover\b', r'\bin any case\b', r'\bclearly\b',
                          r'\bmore and more\b', r'\babsolutely\b', r'\byou know\b', r'\bas a result\b', r'\bbasically\b',
                          r'\bon the whole\b', r'\bi believe\b', r'\bemphasize\b', r'\bin most cases\b', r'\bin reality\b',
                          r'\bfurthermore\b', r'\bthat is to say\b', r'\bi mean\b', r'\bbe sure\b', r'\bseemingly\b',
                          r'\bhighlight\b', r'\bplainly\b', r'\bin my opinion\b', r'\bthe most significant\b',
                          r'\bwith reference to\b', r'\bmore importantly\b', r'\bsurely\b', r'\bunusually\b',
                          r'\bby and large\b', r'\bat any rate\b', r'\binsofar\b', r'\bi see\b', r'\bone aspect of\b',
                          r'\bwell\b\b', r'\bchiefly\b', r'\byou see\b', r'\bto some degree\b', r'\bostensibly\b',
                          r'\bpreferably\b', r'\bin either case\b', r'\bit is evident that\b', r'\bgenerally speaking\b',
                          r'\bforemost\b', r'\bstrictly speaking\b', r'\bas a rule\b', r'\bhonestly\b',
                          r'\bof great importance\b', r'\bbroadly speaking\b', r'\bafter all\b', r'\bin truth\b',
                          r'\bi suppose\b', r'\bof particular importance\b', r'\bideally\b', r'\bchiefly\b',
                          r'\bin the manner of\b', r'\bstrangely\b', r'\binasmuch\b', r'\bsurely\b', r'\bquite simply\b',
                          r'\bunquestionably\b', r'\bfrankly\b', r'\bone way or another\b', r'\btheoretically\b',
                          r'\bof considerable importance\b', r'\bof crucial importance\b', r'\babove all\b', r'\boddly\b',
                          r'\bas it happens\b', r'\ball manner of\b', r'\bit is noteworthy that\b', r'\bmost of all\b',
                          r'\bmost important of all\b', r'\babove all\b', r'\bwithout question\b', r'\bof limited value\b',
                          r'\bof note\b', r'\bof fundamental importance\b', r'\bwithout doubt\b', r'\babove all else\b',
                          r'\bof little value\b', r'\bby any means\b', r'\bwith particular reference to\b',
                          r'\bin neither case\b', r'\bas a matter of fact\b', r'\bit is evident from\b',
                          r'\bof prime importance\b', r'\broughly speaking\b', r'\bin as much as\b',
                          r'\bof paramount importance\b', r'\boutwardly\b', r'\bof critical importance\b',
                          r'\btake note of\b', r'\bculminate\b', r'\bit is inevitable that\b', r'\bof great value\b',
                          r'\bthe climax of\b', r'\bi assume\b', r'\bput simply\b', r'\bof considerable significance\b',
                          r'\bof little significance\b', r'\bof no consequence\b', r'\bi am afraid\b', r'\boddly enough\b',
                          r'\bto be honest\b', r'\bjust\b', r'\bof some value\b', r'\bin actual fact\b', r'\btentatively\b',
                          r'\bto tell the truth\b', r'\bin such a manner as\b', r'\bby all means\b', r'\bregarding\b',
                          r'\bof doubtful value\b', r'\bof major interest\b', r'\bof overriding importance\b',
                          r'\bup until now\b', r'\bof real value\b', r'\badd to that\b', r'\bok\b', r'\bin every aspect\b',
                          r'\bsupposedly\b', r'\btechnically speaking\b', r'\bof equal weight\b',
                          r'\bof less significance\b', r'\bof most value\b', r'\bof profound importance\b',
                          r'\bof strategic importance\b', r'\bas a matter of fact\b', r'\bthe chief characteristics\b',
                          r'\bhypothetically\b', r'\bto be frank\b', r'\bas to\b', r'\bpractically speaking\b',
                          r'\bacademically\b', r'\bit is an undeniable fact that\b', r'\bof primary concern\b',
                          r'\bone particular feature\b', r'\bthe most worrying aspect\b', r'\bthe preferred mode of\b',
                          r'\bthe main issue is\b', r'\bthe major point\b', r'\bthe most necessary\b', r'\boh\b',
                          r'\bto be truthful\b', r'\bwhat i am saying is\b', r'\bthe principal characteristics\b',
                          r'\bcomparatively speaking\b', r'\bbar none\b', r'\bwith all due respect\b',
                          r'\bas i was saying\b', r'\bokay\b', r'\bwithout a shadow of doubt\b'],
        'Comparison': [r'\bas\b', r'\bas .+\bas\b', r'\blike\b', r'\bmore [. ]+ than\b', r'\balso\b', r'\bas well as\b',
                       r'\bless [. ]+ than\b', r'\bin relation to\b', r'\bsimilarly\b', r'\bexactly\b', r'\bunlike\b',
                       r'\bas if\b', r'\bequally\b', r'\bapproximately\b', r'\bsame as\b', r'\broughly\b', r'\bas much as\b',
                       r'\bmatching\b', r'\bas though\b', r'\bparallel to\b', r'\bas distinct from\b', r'\bresembling\b',
                       r'\bin much the same way\b', r'\bin the same way\b', r'\bconcurrently\b', r'\bidentically\b',
                       r'\bcirca\b', r'\bca\.\b', r'\bseparate and distinct from\b', r'\ba different aspect\b',
                       r'\bincongruously\b', r'\bas distinct as\b'],
        'Consequential': [r'\bif\b', r'\bas\b', r'\bbecause\b', r'\btherefore\b', r'\bthen\b', r'\bfor\b', r'\bwhether\b',
                          r'\bthus\b', r'\bbecause of\b', r'\bunless\b', r'\bdue to\b', r'\botherwise\b', r'\bhence\b',
                          r'\beven if\b', r'\bas a result\b', r'\bsince\b', r'\bso\b', r'\bof course\b', r'\baccordingly\b',
                          r'\bwhether or not\b', r'\bconsequently\b', r'\bwith regard to\b', r'\bin response\b',
                          r'\bleading to\b', r'\bin this respect\b', r'\bonly if\b', r'\bprovided that\b',
                          r'\barising from\b', r'\bfor this reason\b', r'\bso long as\b', r'\bsomehow\b', r'\bgiven that\b',
                          r'\bas a consequence\b', r'\bresulting from\b', r'\bresulting from\b', r'\bin that case\b',
                          r'\bresulting in\b', r'\bfor this purpose\b', r'\bbring about\b', r'\bin case\b',
                          r'\bin consequence\b', r'\bin doing so\b', r'\bon account of\b', r'\bgiving rise to\b',
                          r'\barising out of\b', r'\bon this basis\b', r'\bwhat if\b', r'\bto this end\b', r'\blest\b',
                          r'\bforthwith\b', r'\bhenceforth\b', r'\bas a response to\b', r'\bwhereupon\b',
                          r'\bone consequence of\b', r'\bin the event that\b', r'\bwith this in mind\b',
                          r'\bone result of\b', r'\bas a corollary\b', r'\bone effect of\b',
                          r'\bunder the circumstances\b', r'\bthereby\b', r'\bin a nutshell\b',
                          r'\bowing to the fact that\b', r'\bapropos\b', r'\barising out of this\b',
                          r'\bin such an event\b', r'\bwhereby\b'],
        'Contrastive': [r'\bhowever\b', r'\balthough\b', r'\brather\b', r'\bagain\b', r'\bwhile\b', r'\bthough\b',
                        r'\bat least\b', r'\byet\b', r'\bonly\b', r'\bnevertheless\b', r'\bwhereas\b', r'\binstead\b',
                        r'\bexcept\b', r'\bon the other hand\b', r'\bthen\b', r'\bwhilst\b', r'\beven though\b',
                        r'\bin contrast\b', r'\bbut\b', r'\bon the one hand\b', r'\bworse\b', r'\bby contrast\b',
                        r'\bin fact\b', r'\bas opposed to\b', r'\bafter all\b', r'\bat the same time\b', r'\balbeit\b',
                        r'\bconversely\b', r'\bversus\b', r'\bbesides\b', r'\bactually\b', r'\bin any event\b',
                        r'\bnonetheless\b', r'\banyway\b', r'\bon the contrary\b', r'\bin comparison\b', r'\badmittedly\b',
                        r'\bnotwithstanding\b', r'\bironically\b', r'\bparadoxically\b', r'\bin place of\b',
                        r'\bin any case\b', r'\bby comparison\b', r'\bnotwithstanding\b', r'\b\bvs\.\b',
                        r'\bmore accurately\b', r'\balternatively\b', r'\bunexpectedly\b', r'\balternatively\b',
                        r'\ball the same\b', r'\bthen again\b', r'\bfor all that\b', r'\bmore precisely\b', r'\banyhow\b',
                        r'\bat any rate\b', r'\brather better\b', r'\bby way of contrast\b', r'\bthat said\b',
                        r'\bdespite that\b', r'\bcontrariwise\b', r'\banother distinction\b', r'\bas a matter of fact\b',
                        r'\bby way of comparison\b', r'\boppositely\b', r'\ba striking difference\b', r'\belse\b',
                        r'\bin spite of that\b'],
        'Sequential': [r'\bwhen\b', r'\bafter\b', r'\bbefore\b', r'\bsince\b', r'\bduring\b', r'\bnow\b', r'\blater\b',
                       r'\bfollowing\b', r'\balways\b', r'\buntil\b', r'\bone\b', r'\bonce\b', r'\bsometimes\b',
                       r'\bearlier\b', r'\bnever\b', r'\b[abcdi\d]\)[. ]+\b', r'\bthe latter\b', r'\bdirectly\b',
                       r'\bpreviously\b', r'\bfrequently\b', r'\bnow\b', r'\bfinally\b', r'\brecently\b', r'\bimmediately\b',
                       r'\bthe former\b', r'\bsecond\b', r'\bsubsequently\b', r'\beventually\b', r'\bsecondly\b',
                       r'\bat the same time\b', r'\bso far as\b', r'\bhere\b', r'\brarely\b', r'\binitially\b',
                       r'\btherefore\b', r'\bultimately\b', r'\bquickly\b', r'\bcurrently\b', r'\bsoon\b', r'\boriginally\b',
                       r'\boccasionally\b', r'\bgradually\b', r'\bfirstly\b', r'\bat present\b', r'\bthird\b',
                       r'\bsimultaneously\b', r'\bthe first time\b', r'\bconstantly\b', r'\bslowly\b', r'\bwhile\b',
                       r'\bas long as\b', r'\bin the future\b', r'\bin the first place\b', r'\bas soon as\b', r'\bfirst\b',
                       r'\bat this point\b', r'\bthirdly\b', r'\bseldom\b', r'\bin the end\b', r'\bas yet\b',
                       r'\bhitherto\b', r'\bsuddenly\b', r'\bmeanwhile\b', r'\btwo\b', r'\bgenerally\b', r'\bby the time\b',
                       r'\bformerly\b', r'\bfrom time to time\b', r'\brepeatedly\b', r'\btemporarily\b', r'\btill\b',
                       r'\boften\b', r'\busually\b', r'\bpresently\b', r'\bincidentally\b', r'\bfirst of all\b',
                       r'\bnot at all\b', r'\bsoon after\b', r'\blastly\b', r'\bthree\b', r'\bto begin with\b',
                       r'\bby now\b', r'\bin the meantime\b', r'\binfrequently\b', r'\bnext\b',
                       r'\bat the time of writing\b', r'\blater on\b', r'\bfor the first time\b', r'\bperiodically\b',
                       r'\bthereafter\b', r'\bbeforehand\b', r'\ball right\b', r'\bby the way\b',
                       r'\bat the present time\b', r'\bthe length of time\b', r'\bfor one thing\b', r'\bto start with\b',
                       r'\binstantly\b', r'\bmost of the time\b', r'\bmeanwhile\b', r'\beventually\b',
                       r'\bas a starting point\b', r'\bthe amount of time\b', r'\bhereafter\b', r'\bnowadays\b',
                       r'\bsooner or later\b', r'\bduring this time\b', r'\bat any given time\b', r'\bup to now\b',
                       r'\bconclude\b', r'\bwithout exception\b', r'\bfrom now on\b', r'\bbut this time\b',
                       r'\bone at a time\b', r'\bin the second place\b', r'\bat the right time\b', r'\baforementioned\b',
                       r'\balright\b', r'\bfor much of the time\b', r'\bshortly\b', r'\blast\b', r'\bnow and then\b',
                       r'\bthe following week\b', r'\bafter a time\b', r'\ball at once\b', r'\bafter a while\b',
                       r'\bat any other time\b', r'\bwith the passage of time\b', r'\bprior to this\b',
                       r'\ball the while\b', r'\bmeantime\b', r'\bsome of the time\b', r'\bfor the last time\b',
                       r'\bhenceforward\b', r'\bin the same time\b', r'\bhenceforth\b', r'\bjust then\b',
                       r'\blittle by little\b', r'\bnow and again\b', r'\bfor long periods of time\b',
                       r'\bthere was a time\b', r'\btime and time again\b', r'\bit was at this time\b', r'\bmind you\b',
                       r'\ball of the time\b', r'\bnot long ago\b', r'\bafore\b', r'\bfor another thing\b',
                       r'\band all the time\b', r'\bas a final point\b', "\bin a year's time\b",
                       r'\bin the fullness of time\b', r'\blast of all\b', r'\btime to move on\b',
                       r'\bin a very short time\b', r'\bafter a short time\b', r'\bafterward\b', r'\bto top it all\b',
                       r'\bsecond of all\b', r'\bby the by\b', r'\bas of yet\b', r'\bit is about time\b',
                       r"\bin a fortnight's time\b"],
        'Summation': [r'\bthus\b', r'\bin all\b', r'\boverall\b', r'\bthen\b', r'\bbriefly\b', r'\baltogether\b',
                      r'\bconclude\b', r'\bin short\b', r'\bfinally\b', r'\bin conclusion\b', r'\bin summary\b',
                      r'\bsum up\b', r'\bsummarize\b', r'\bin a word\b', r'\bin sum\b', r'\ball in all\b', r'\bresume\b',
                      r'\bget back to the point\b'],
        'Attribution': ['accepts', 'accounts for', 'acknowledges', 'addresses', 'adds', 'admits', 'advises', 'affirms',
                        'agrees', 'alleges', 'allows', 'analyzes', 'answers', 'argues', 'asks', 'asserts', 'assumes',
                        'believes', 'categorizes', 'challenges', 'charges', 'cites', 'claims', 'comments', 'compares',
                        'complains', 'concedes', 'concludes', 'concurs', 'confesses', 'confirms', 'considers',
                        'contends', 'contents', 'criticizes', 'deals with', 'decides', 'declares', 'defines', 'denies',
                        'describes', 'disagrees', 'discusses', 'disputes', 'emphasizes', 'emphasizes', 'endorses',
                        'exclaims', 'explains', 'expresses', 'finds', 'grants', 'hypothesizes', 'illustrates',
                        'implies', 'indicates', 'insinuates', 'insists', 'interprets', 'introduces', 'lists',
                        'maintains', 'mentions', 'mumbles', 'notes', 'objects', 'observes', 'offers', 'opposes',
                        'points out', 'proposes', 'questions', 'realizes', 'reasons', 'refutes', 'rejects', 'remarks',
                        'replies', 'reports', 'responds', 'reveals', 'sees', 'shows', 'speculates', 'states',
                        'suggests', 'supports', 'supposes', 'thinks', 'uses', 'utilizes', 'verifies', 'whines',
                        'writes']
    },
    'pairs_words': {
        'first_pair_x': ['\baccording to\b', '\bafter\b', '\balso\b', '\balthough\b', '\band\b', '\bas\b', '\baside\b',
                         '\bbecause of\b', '\bbecause\b', '\bbefore\b', '\bbut\b', '\bcurrently\b', '\beven\b',
                         '\bexcept\b', '\bfollowing\b', '\bfor example\b', '\bfor instance\b', '\bfor\b', '\bhowever\b',
                         '\bif\b', '\bin addition\b', '\bjust\b', '\blast\b', '\blike\b', '\bmoreover\b', '\bnext\b',
                         '\bnow\b', '\boften\b', '\bonce\b', '\bone\b', '\brather\b', '\bresume\b', '\bsince\b',
                         '\bsoon after\b', '\bthough\b', '\bthree\b', '\bto illustrate\b', '\btwo\b', '\bunless\b',
                         '\bunlike\b', '\buntil\b', '\bwell\b\b', '\bwhen\b', '\bwhether\b', '\bwhile\b',
                         '\bwithout question\b', 'charges', 'claims', 'comments', 'reports', 'states'],
        'last_pair_x': ['\bas\b', '\bfirst\b', '\bfor\b', '\bfurther\b', '\bhowever\b', '\blast\b', '\bmuch\b',
                        '\bnow\b', '\bone\b', '\bparticularly\b', '\bso\b', '\bsoon\b', 'answers', 'concedes',
                        'reports', 'suggests'],
        'first_pair_y': ['\baccording to\b', '\bafter\b', '\balternatively\b', '\balthough\b', '\band\b', '\bas if\b',
                         '\bas though\b', '\bas\b', '\bbecause\b', '\bbefore\b', '\bbut\b', '\bcertainly\b',
                         '\beither\b', '\beven if\b', '\beven\b', '\bfirst\b', '\bfollowing\b', '\bfor\b',
                         '\bhowever\b', '\bideally\b', '\bif\b', '\bindeed\b', '\binstead\b', '\bjust\b', '\blast\b',
                         '\blike\b', '\bmore\b', '\bnever\b', '\bnext\b', '\bnow\b', '\boften\b', '\bor\b',
                         '\botherwise\b', '\bpreviously\b', '\brather\b', '\bseldom\b', '\bsince\b', '\bso\b',
                         '\bthe former\b', '\bthen\b', '\btherefore\b', '\bthough\b', '\bthree\b', '\bthus\b',
                         '\bunless\b', '\bunlike\b', '\buntil\b', '\bwell\b\b', '\bwhen\b', '\bwhether\b', '\bwhile\b',
                         '\byet\b', 'lists', 'notes', 'questions', 'sees', 'uses'],
        'last_pair_y': ['\balso\b', '\bcurrently\b', '\bearlier\b', '\bfurther\b', '\blast\b', '\bmuch\b',
                        '\bnonetheless\b', '\bnow\b', '\bone\b', '\bwell\b\b', 'charges', 'decides', 'writes']
    }
}

# Compile the vocabularies

vocabs = {
    'ru': VOCAB_RU,
    'en': VOCAB_EN
}

for lang in vocabs:
    vocabs[lang]['count_words_x'] = [re.compile(marker, re.I) for marker in vocabs[lang]['count_words_x']]
    vocabs[lang]['count_words_y'] = [re.compile(marker, re.I) for marker in vocabs[lang]['count_words_y']]

    for key in vocabs[lang]['markers_by_classes'].keys():
        vocabs[lang]['markers_by_classes'][key] = [re.compile(r'' + marker, re.I) for marker in
                                                   vocabs[lang]['markers_by_classes'][key]]

    for key in vocabs[lang]['pairs_words'].keys():
        vocabs[lang]['pairs_words'][key] = [re.compile(r'' + marker, re.I) for marker in
                                            vocabs[lang]['pairs_words'][key]]
